import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import './globals.css'
import type { Metadata } from 'next'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import Heart from '@/components/Heart'





export const metadata: Metadata = {
  title: 'Image Valley',
  description: 'Generated by create next app',
}
function SideBar(){
  return (
    <div className="pb-12 w-1/5">
    <div className="space-y-4 py-4">
      <div className="px-3 py-2">
      
        <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
        Manage
        </h2>
        
        <div className="space-y-1 ">
        <Link href="/gallery">
          <Button variant="ghost" className="w-full justify-start flex gap-4">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
</svg>
            Gallery
          </Button>
            </Link>
          <Button variant="ghost" className="w-full justify-start flex gap-4">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
</svg>


          Albums
          </Button>
         <Link href="/favorites">
         <Button variant="ghost" className="w-full justify-start flex gap-4">
  
         <Heart/>
   Favorites
</Button>
         </Link>
        </div>
      </div>
      </div>
      </div>
  )
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body> 
    
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            PHOTO GALLERY
            <div className="ml-auto flex items-center space-x-4">
            <Avatar>
      <AvatarImage src="https://avatars.githubusercontent.com/u/129727756?v=4" alt="@shadcn" />
      <AvatarFallback>CN</AvatarFallback>
    </Avatar>
            </div>
          </div>
        </div>
        <div className='flex'>

      <SideBar/>
          
      <div className='w-full pt-12 px-4'>{children}</div>
        </div>
      
        
        </body>
    </html>
  )
}
