
import ImageCard from "./ImageCard"
import type { Metadata } from 'next'
import UploadButton from "./upload-button"
import cloudinary from 'cloudinary'

 export type SearchResults={
    public_id:string
    tags:string[]
}
export const metadata: Metadata = {
  title: 'Gallery',
  description: 'Generated by create next app',
}

export default async function Page(){
  
   const results= await cloudinary.v2.search
  .expression('resource_type:image')
  .sort_by('created_at','desc')
  .max_results(30)
  .with_field('tags')
  .execute() as {resources:SearchResults[]}

  function getColumns(colIndex:number){
   return results.resources.filter((resource,i)=>i% 4=== colIndex
    )
  }
 
    return (
        <section>
            <div className="flex justify-between">
               <h1 className="font-bold text-4xl ">Gallery</h1>
               <UploadButton />
            </div>
                <div className="grid grid-cols-4 mt-8 gap-4">
                  {[
                    getColumns(0),
                    getColumns(1),
                    getColumns(2),
                    getColumns(3)
                  ].map((column,i)=>(
                  <div className="flex flex-col gap-4" key={i}>
                      
                  {column.map((image)=>(
                    <ImageCard  width="400"
                     key={image.public_id}
                     path="/gallery"
                    height="300"
                    imageData={image}
                    sizes="100vw"
                    alt="Description of my image"
                    className="hover:opacity-[0.5] cursor-pointer rounded-3xl"/>
                  ))}
                  </div>))}
                </div>
        </section>
    )

}