
import ImageCard from "../gallery/ImageCard"
import type { Metadata } from 'next'

import cloudinary from 'cloudinary'
import { SearchResults } from "../gallery/page"

export const metadata: Metadata = {
  title: 'Favroite Images',
  description: 'Generated by create next app',
}
export default async function Page(){

   const results= await cloudinary.v2.search
  .expression('resource_type:image AND tags=favorite')
  .sort_by('created_at','desc')
  .max_results(30)
  .with_field('tags')
  .execute() as {resources:SearchResults[]}

 
    return (
        <section>
            <div className="flex justify-between">
               <h1 className="font-bold text-4xl ">Favorites Images</h1>
        
            </div>
                <div className="grid grid-cols-4 mt-8 gap-4">
                  {results.resources.map((image)=>(
                    <ImageCard  width="400"
                     key={image.public_id}
                     path="/favorites"
                    height="300"
                    imageData={image}
                    sizes="100vw"
                    alt="Description of my image"
                    className="hover:opacity-[0.5] cursor-pointer rounded-3xl"/>
                  ))}
                </div>
        </section>
    )

}